version: '3.1'

services:

  drupal:
    image: drupal:8-apache
    ports:
      - 8080:80
    networks:
      - drupal
    restart: always

  postgres:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
    networks:
      - drupal

networks:
  drupal:
   driver: bridge 